//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordShack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblArtist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArtist()
        {
            this.tblRecords = new HashSet<tblRecord>();
        }
    
        public int ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string ArtistBio { get; set; }
        public string ImageSrc { get; set; }
        public string ImageAlt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecord> tblRecords { get; set; }

        public tblArtist(string name, string bio, string imgsrc, string imgalt)
        {
            RecordShackCMSEntities context = new RecordShackCMSEntities();

            ArtistName = name;
            ArtistBio = bio;
            ImageSrc = imgsrc;
            ImageAlt = imgalt;

            ArtistID = context.tblArtists.OrderByDescending(x => x.ArtistID).FirstOrDefault().ArtistID + 1;
        }
    }
}
