//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordShack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblGenre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGenre()
        {
            this.tblRecords = new HashSet<tblRecord>();
        }
    
        public int GenreID { get; set; }
        public string GenreName { get; set; }
        public string GenreBio { get; set; }
        public string ImageSrc { get; set; }
        public string ImageAlt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecord> tblRecords { get; set; }

        public tblGenre(string name, string bio, string imgsrc, string imgalt)
        {
            RecordShackCMSEntities context = new RecordShackCMSEntities();

            GenreName = name;
            GenreBio = bio;
            ImageSrc = imgsrc;
            ImageAlt = imgalt;

            GenreID = context.tblGenres.OrderByDescending(x => x.GenreID).FirstOrDefault().GenreID + 1;
        }
    }
}
