//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordShack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblRating
    {
        public int RatingID { get; set; }
        public int RecordID { get; set; }
        public int UserID { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }
    
        public virtual tblRecord tblRecord { get; set; }
        public virtual tblUser tblUser { get; set; }

        public tblRating()
        {

        }

        public tblRating(int recordid, string comment, int rating, string username)
        {
            RecordID = recordid;
            Comment = comment;
            Rating = rating;

            RecordShackCMSEntities context = new RecordShackCMSEntities();
            RatingID = context.tblRatings.OrderByDescending(x => x.RatingID).FirstOrDefault().RatingID + 1;
            UserID = context.tblUsers.Where(u => u.UserName.ToLower() == username.ToLower()).Select(u => u.UserID).FirstOrDefault();
        }
    }
}
