//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordShack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRecord()
        {
            this.tblRatings = new HashSet<tblRating>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public string RecordName { get; set; }
        public string RecordBio { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ImageSrc { get; set; }
        public string ImageAlt { get; set; }
    
        public virtual tblArtist tblArtist { get; set; }
        public virtual tblGenre tblGenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRating> tblRatings { get; set; }

        public tblRecord(int artistid, int genreid, string name, string bio, DateTime releasedate, string imgsrc, string imgalt)
        {
            RecordShackCMSEntities context = new RecordShackCMSEntities();

            ArtistID = artistid;
            GenreID = genreid;
            RecordName = name;
            RecordBio = bio;
            ReleaseDate = releasedate;
            ImageSrc = imgsrc;
            ImageAlt = imgalt;

            RecordID = context.tblRecords.OrderByDescending(x => x.RecordID).FirstOrDefault().RecordID + 1;
        }
    }
}
