//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordShack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblRatings = new HashSet<tblRating>();
            this.tblUserRoles = new HashSet<tblUserRole>();
        }

        public tblUser(string username, string emailaddress, string password)
        {
            UserName = username;
            EmailAddress = emailaddress;
            Password = password;

            RecordShackCMSEntities context = new RecordShackCMSEntities();
            UserID = context.tblUsers.OrderByDescending(u => u.UserID).FirstOrDefault().UserID + 1;
        }

        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRating> tblRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRole> tblUserRoles { get; set; }
    }
}
